networks:
  extsvcs:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ognet
    ports:
      - "8444:8444"
    volumes:
      - /var/lib/docker/volumes/ognet/_data:/db
    environment:
      DATABASE_URL: "sqlite:////db/test.db"
      SMTP_SERVER: "smtp.ibondar.pro"
      SMTP_PORT: 587
      SMTP_USER: "user@ibondar.pro"
      SMTP_PASSWORD: "yourpassword"
      EMAIL_FROM: "noreply@ibondar.pro"
      EMAIL_TO: "admin@ibondar.pro"
    networks:
      - extsvcs
    restart: always
